language: cpp
compiler:
  - gcc
  - clang
before_install:
  - rvm use $RVM --install --binary --fuzzy
before_script:
  - ./configure $RBX_MODE
branches:
  only:
    - master
    - compiler
notifications:
  recipients:
    - evan+notify@phx.io
    - brixen@gmail.com
    - d.bussink@gmail.com
  email:
    on_success: change
    on_failure: always
env:
  - RVM=1.8.7
  - RVM=1.9.3
  - RBX_MODE=18
  - RBX_MODE=21
