language: cpp
compiler:
  - gcc
  - clang
before_install:
  - rvm use $RVM --install --binary --fuzzy
  - gem update --system
  - gem --version
before_script:
  - travis_retry bundle
  - travis_retry ./configure --skip-stdlib
script: rake
branches:
  only:
    - master
    - compiler
notifications:
  recipients:
    - brixen@gmail.com
    - d.bussink@gmail.com
  email:
    on_success: change
    on_failure: always
env:
  - RVM=2.0.0
