name: Rubinius CI

on: [push]

jobs:
  build:
    if: true
    strategy:
      matrix:
        os: [ ubuntu-16.04 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - run: sudo apt-get update
    - run: sudo apt-get install ruby
    - name: Install dependencies
      run: ./scripts/dependencies.sh
    - name: Configure
      run: ./configure --llvm-config=llvm-config --cc=clang --cxx=clang++
    - name: Build
      run: make
    - name: VM Tests
      run: rake -q vm:test
    - name: Specs
      run: bin/mspec ci
